### ISSUE TITLE
[LEAGUE LOADER]: Running ESPN example gives TypeError: dataclass() got an unexpected keyword argument 'kw_only'

### ISSUE THREAD

**Issue by lhersman** [joeyagreco/leeger#25]
### League Loader

ESPN

### Summary

Win10, using Python 3.8.5
I attempted to run the ESPN example, found the relevant data for private league and ran and got
`TypeError: dataclass() got an unexpected keyword argument 'kw_only'`

I found a similar issue googling around which suggested running `pip install attrs --upgrade` to fix but that did not help.  Any advice would be apricated. Thanks!

### Error Logs

Traceback (most recent call last):
  File "C:\Python38\Lib\site-packages\leeger\league_loader\ESPNShadowStalkers.py", line 1, in <module>
    from leeger.league_loader import ESPNLeagueLoader
  File "C:\Python38\lib\site-packages\leeger\league_loader\__init__.py", line 1, in <module>
    from .ESPNLeagueLoader import ESPNLeagueLoader
  File "C:\Python38\lib\site-packages\leeger\league_loader\ESPNLeagueLoader.py", line 6, in <module>
    from leeger.league_loader.LeagueLoader import LeagueLoader
  File "C:\Python38\lib\site-packages\leeger\league_loader\LeagueLoader.py", line 5, in <module>
    from leeger.model.league.League import League
  File "C:\Python38\lib\site-packages\leeger\model\league\__init__.py", line 1, in <module>
    from .League import League
  File "C:\Python38\lib\site-packages\leeger\model\league\League.py", line 6, in <module>
    from leeger.model.league.Owner import Owner
  File "C:\Python38\lib\site-packages\leeger\model\league\Owner.py", line 9, in <module>
    @dataclass(kw_only=True, eq=False)

**Comment by joeyagreco** [comment]
This library only works on Python 3.10+

I'm not sure if there's an official way to indicate that so I just made it a badge on the README.

![image](https://user-images.githubusercontent.com/57115019/188776187-315a0254-bd93-472f-8af2-c38a5277b19c.png)
